import { useCallback, useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { api } from '../api'
import { Badge, Button, Chip, ConfirmDialog, Empty, Spinner, Tabs, useToast } from '../components/ui'
import { Icon } from '../components/Icon'
import { FormField } from '../components/FormField'
import type { Coupon, ShopCoupon } from '../types'
import { userFacingError } from '../utils/errors'
import { formatThaiDateTime } from '../utils/format'
import { useShopAccess } from './shopAccess'

const EMPTY_FORM = { title: '', description: '', coin_cost: '', qr_payload: '', valid_until: '' }
type CouponFormValues = typeof EMPTY_FORM

export default function ShopCoupons() {
  const access = useShopAccess(); const [params, setParams] = useSearchParams(); const { toast, showToast } = useToast()
  const [tab, setTab] = useState<'own' | 'all'>(params.get('tab') === 'all' ? 'all' : 'own')
  const [coupons, setCoupons] = useState<Coupon[]>([]); const [network, setNetwork] = useState<ShopCoupon[]>([])
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const [showForm, setShowForm] = useState(false); const [form, setForm] = useState(EMPTY_FORM); const [confirm, setConfirm] = useState<Coupon | null>(null)
  const load = useCallback(async () => { setLoading(true); try { const [own, peers] = await Promise.all([api.get<{ coupons: Coupon[] }>('/my-shop/coupons'), api.get<{ coupons: ShopCoupon[] }>('/my-shop/network-coupons')]); setCoupons(own.coupons); setNetwork(peers.coupons); setError('') } catch (err) { setError(userFacingError(err, 'โหลดข้อมูลร้านไม่ได้ กรุณาลองใหม่')) } finally { setLoading(false) } }, [])
  useEffect(() => { if (!access.loading && !access.error) load() }, [access.loading, access.error, load])
  const changeTab = (next: 'own' | 'all') => { setTab(next); setParams(next === 'all' ? { tab: 'all' } : {}, { replace: true }) }
  const create = async (e: React.FormEvent) => { e.preventDefault(); setBusy(true); try { await api.post('/my-shop/coupons', { ...form, coin_cost: Number(form.coin_cost), valid_until: new Date(form.valid_until).toISOString(), description: form.description || undefined }); setForm(EMPTY_FORM); setShowForm(false); await load() } catch (err) { showToast(userFacingError(err)) } finally { setBusy(false) } }
  const deactivate = async () => { if (!confirm) return; setBusy(true); try { await api.delete(`/my-shop/coupons/${confirm.id}`); setConfirm(null); await load() } catch (err) { showToast(userFacingError(err)) } finally { setBusy(false) } }
  if (access.loading) return <Spinner />
  if (access.error) return <State text={access.error} retry={() => window.location.reload()} />
  if (loading) return <Spinner />
  return <div style={S.page}><header style={S.nav}><b>จัดการคูปองร้านค้า</b>{tab === 'own' && <button onClick={() => setShowForm(true)} style={S.add}>+</button>}</header><Tabs value={tab} onChange={value => changeTab(value as 'own' | 'all')} tabs={[{ value: 'own', label: 'คูปองรางวัล' }, { value: 'all', label: 'คูปองทั้งหมด' }]} />{error && <State text={error} retry={load} />}
    {tab === 'own' ? <main style={S.content}><Button fullWidth size="lg" onClick={() => setShowForm(true)}>＋ เพิ่มคูปองรางวัล</Button>{coupons.filter(c => c.active).length === 0 ? <Empty text="ยังไม่มีคูปอง กดเพิ่มคูปองด้านบน" /> : coupons.filter(c => c.active).map(c => <div key={c.id} style={S.card}><div style={{ flex: 1 }}><b>{c.title}</b>{c.description && <p>{c.description}</p>}<Chip>฿ {c.coin_cost}</Chip> <Chip>หมดอายุ {formatThaiDateTime(c.valid_until)}</Chip><small style={S.small}>QR: {c.qr_payload.slice(0, 24)}{c.qr_payload.length > 24 ? '…' : ''}</small></div><button onClick={() => setConfirm(c)} disabled={busy} style={S.delete}><Icon name="trash" size={22} /></button></div>)}</main> : <main style={S.content}>{network.length === 0 ? <Empty text="ยังไม่มีคูปองจากร้านอื่นใน Host นี้" /> : network.map(c => <div key={c.id} style={{ ...S.card, ...(c.shop.is_current ? S.ownCard : {}) }}><div>{c.shop.is_current ? <Badge label="ร้านของฉัน" /> : <small style={S.shop}>{c.shop.name}</small>}<b>{c.title}</b>{c.description && <p>{c.description}</p>}<Chip>฿ {c.coin_cost}</Chip> <Chip>หมดอายุ {formatThaiDateTime(c.valid_until)}</Chip></div></div>)}</main>}
    {showForm && <CouponForm form={form} setForm={setForm} busy={busy} onClose={() => { setShowForm(false); setForm(EMPTY_FORM) }} onSubmit={create} />}{confirm && <ConfirmDialog title="ปิดคูปอง" message={`หยุดแสดง "${confirm.title}"?`} confirmLabel="ปิดคูปอง" destructive onConfirm={deactivate} onCancel={() => setConfirm(null)} />}{toast}</div>
}
function CouponForm({ form, setForm, busy, onClose, onSubmit }: { form: CouponFormValues; setForm: React.Dispatch<React.SetStateAction<CouponFormValues>>; busy: boolean; onClose: () => void; onSubmit: (event: React.FormEvent) => void }) { return <div style={S.overlay}><div style={S.form}><button onClick={onClose} style={S.close}>×</button><h3>เพิ่มคูปอง</h3><form onSubmit={onSubmit}>{(['title', 'description', 'coin_cost', 'qr_payload', 'valid_until'] as const).map(name => <FormField key={name} label={`${name === 'title' ? 'ชื่อคูปอง' : name === 'description' ? 'รายละเอียด' : name === 'coin_cost' ? 'ราคาเหรียญ' : name === 'qr_payload' ? 'QR Payload' : 'วันหมดอายุ'}${name === 'description' ? '' : ' *'}`} style={{ marginBottom: 12 }}><input required={name !== 'description'} type={name === 'coin_cost' ? 'number' : name === 'valid_until' ? 'datetime-local' : 'text'} value={form[name]} onChange={e => setForm(v => ({ ...v, [name]: e.target.value }))} style={S.input} /></FormField>)}<Button type="submit" fullWidth size="lg" disabled={busy}>{busy ? 'กำลังบันทึก...' : 'บันทึก'}</Button></form></div></div> }
function State({ text, retry }: { text: string; retry: () => void }) { return <section style={S.state}><p>{text}</p><Button size="sm" variant="outline" onClick={retry}>ลองใหม่</Button></section> }
const S: Record<string, React.CSSProperties> = { page: { maxWidth: 430, minHeight: '100vh', margin: '0 auto', background: 'var(--background-secondary)' }, nav: { height: 50, display: 'flex', alignItems: 'center', justifyContent: 'center', position: 'relative', background: 'var(--surface)' }, add: { position: 'absolute', right: 12, border: 0, borderRadius: '50%', width: 34, height: 34, color: '#fff', background: 'var(--primary)', fontSize: 22 }, content: { display: 'grid', gap: 12, padding: 16 }, card: { display: 'flex', gap: 10, padding: 16, borderRadius: 'var(--radius-lg)', background: 'var(--surface)', boxShadow: 'var(--shadow-sm)', border: '2px solid transparent' }, ownCard: { border: '2px solid var(--primary)' }, small: { display: 'block', marginTop: 8, color: 'var(--text-tertiary)' }, shop: { display: 'block', color: 'var(--primary)', fontWeight: 800, marginBottom: 5 }, delete: { border: 0, background: 'transparent', color: 'var(--danger)' }, state: { margin: 16, padding: 16, textAlign: 'center', background: 'var(--surface)', borderRadius: 'var(--radius-md)' }, overlay: { position: 'fixed', inset: 0, zIndex: 10, display: 'grid', placeItems: 'center', padding: 16, background: 'var(--dim)' }, form: { position: 'relative', width: '100%', maxWidth: 350, padding: 20, borderRadius: 'var(--radius-lg)', background: 'var(--surface)' }, close: { position: 'absolute', right: 12, top: 8, border: 0, background: 'transparent', fontSize: 24 }, input: { width: '100%', height: 42, padding: 8, border: '1px solid var(--border)', borderRadius: 'var(--radius-sm)' } }
